---
title: "Create a CSV report using the command line"
description: "Create a CSV report using the command line tool, curl."
products: 
    - "reports"
introduction: 
    title: "介绍"
    description: "Learn how to use the Reports API"
    content: "# Introduction\n\nThis tutorial shows you how to create and retrieve reports using the asynchronous version of the Reports API.\n\nTo generate a report, you submit a report generation request to the ASYNC endpoint and wait for it to be processed.\n\nThe Reports API checks whether the format of the request is correct, then places it in the processing queue. It responds with a link that enables you to check the current status of the report. The Reports API can also send a callback to notify your application when the report has been generated.\n\n> **A note on performance**: Even though the Reports API is fast and can deal with enormous amounts of data, it may becomer slower when trying to download data for realtime analytics. Using sensible filters can speed up processing considerably. Also, for frequent and periodic retrievals of small batches of data records please consider using a synchronous version of the Reports API.\n"
tasks: 
    - "reports/create-report"
    - "reports/check-report-status"
    - "reports/download-report"
    - "reports/reports-whats-next"
