---
title: "Making an in-app voice call"
description: "Make a voice call from a web app to a phone."
products: 
    - "client-sdk"
introduction: 
    title: "Introduction to this task"
    description: "This task shows you how to use make a phone call from a web app using the JavaScript Client SDK."
    content: "# Introduction\nIn this tutorial, you will learn how to create a Client SDK application and then write the code to make a\nphone call from your web app to a phone.\n\nTo achieve this, you will need:\n\n* A web application that will make the voice call using the Client SDK.\n* A publicly accessible URL that serves instructions on how to handle the call. You will use a GitHub Gist to accomplish this. <a href=\"https://gist.github.com/\" target=\"_blank\">GitHub Gists</a> are a simple way to share code snippets with others.\n"
prerequisites: 
    - "create-nexmo-account"
    - "install-nodejs"
    - "client-sdk/install-node-client-sdk"
    - "install-nexmo-cli-beta"
    - "join-github"
tasks: 
    - "client-sdk/app-to-phone/create-ncco"
    - "client-sdk/app-to-phone/create-application"
    - "client-sdk/create-user"
    - "client-sdk/generate-jwt-alice"
    - "client-sdk/app-to-phone/js-code"
    - "client-sdk/app-to-phone/js-run"
conclusion: 
    title: "What's next?"
    description: "What else can you do with the Client SDK?"
    content: "\n# What's next?\nYou can do a lot more with the Client SDK.\n\nWe want to hear what ideas you have in mind? Contact us at [devrel@vonage.com](mailto:devrel@vonage.com)\n\nSee [Client SDK documentation](/client-sdk/overview).\n"
