title: Interactive Voice Response with Node.js
description: Build an automated phone system for users to input information with the keypad and hear a spoken response with Node.js
products:
 - voice/voice-api

introduction: 
  title: Introduction to this tutorial
  description: This tutorial shows you how to build an automated phone system using Node.js, where callers request information using the keypad and hear a spoken response.
  content: |
    # Interactive Voice Response

    For users with a simple enquiry, make it easy and quick for them by offering an Interactive Voice Response (IVR) service. This tutorial will walk you through building an application to do exactly that with simple text-to-speech (TTS) prompts and keypad input.
  
    The scenario is this: a customer phones a delivery company to find out the status of their order. They are prompted to enter their order number and then hear a spoken response that tells them the status of their order. (The status is generated randomly in this example).
  
    This tutorial is based on the [Simple IVR](/use-cases/interactive-voice-response) use case. All the code is available on [GitHub](https://github.com/spiritbro1/nodejs-phone-menu).

prerequisites:
- create-nexmo-account
- install-nodejs

tasks:
- voice-api/ivr-node/setting-up-for-ivr
- voice-api/ivr-node/create-a-voice-application
- voice-api/ivr-node/buy-a-phone-number
- voice-api/ivr-node/link-phone-number-to-the-nexmo-application
- voice-api/ivr-node/try-it-yourself
- voice-api/ivr-node/handle-an-inbound-call
- voice-api/ivr-node/generate-nccos
- voice-api/ivr-node/send-text-to-speech-greeting
- voice-api/ivr-node/request-user-input-via-ivr
- voice-api/ivr-node/respond-to-user-input
- voice-api/ivr-node/tips-for-better-text-to-speech
- voice-api/ivr-node/conclusion

conclusion:
  title: Next Steps
  description: What else can you do with the Voice API?
  content: |
    ## Next Steps

    Here are a few more resources that could be useful for building this type of application:

    * [Text-To-Speech Guide](https://developer.nexmo.com/voice/voice-api/guides/customizing-tts) - includes the different voices on offer and information about SSML (Speech Synthesis Markup Language) for better control of the spoken output.
    * [Twitter IVR](https://www.nexmo.com/blog/2018/06/26/twitter-interactive-voice-response-dr/) - another fairly silly example but a great example app written in Python.
    * [Text To Speech With Prompt Calls Using Python on AWS Lambda](https://www.nexmo.com/blog/2018/02/16/text-speech-prompt-calls-using-python-aws-lambda-dr/) - a similar application but this time using AWS Lambda (a serverless platform) and Python.
    * [Code Samples for handling DTMF](https://developer.nexmo.com/voice/voice-api/code-snippets/handle-user-input-with-dtmf) - examples in various programming languages for handling the user keypad input as used in this tutorial.
  

    
