---
title: "セキュリティとスパム防止のための2要素認証"
description: "Rubyアプリケーションで2faを実装する方法を学ぶ"
products: 
    - "検証"
introduction: 
    title: "はじめに"
    description: "Rubyアプリケーションで2faを実装する方法を学ぶ"
    content: "#はじめに\n\nユーザー名とパスワードの認証は、ほぼすべての場所で使用されますが、多くの場合、それほど安全ではありません。良いパスワードは覚えにくいことがあるため、複数のアカウントのものを書き留めたり、再利用したりすることがよくあります。また、サービスに登録するユーザー名とパスワードだけに頼ると、スパムを送信する偽のアカウントを複数作成するボットネットワークに対して脆弱になります。\n\nボットネットがこれらのアカウントを作成するのを停止する良い方法の1つは、2要素認証（2fa）を使用することです。登録時に電話番号をアカウントにリンクし、ログインするたびにその番号に送信されるPINの入力をユーザーに要求します。これはCAPTCHAやソーシャルログインよりもスパムに対してはるかに効果的です。\n\nこのチュートリアルでは、Verify APIを使用して、お使いのRubyアプリケーションで2faを実装する方法を学びます。\n"
tasks: 
    - "verify/2fa-ruby-basic-web-app"
    - "verify/2fa-ruby-add-number-to-model"
    - "verify/2fa-ruby-send-verify-request"
    - "verify/2fa-ruby-check-code"
    - "verify/2fa-ruby-try-it-out"
