---
title: How to Receive an SMS Message with ASP.NET Core MVC and SignalR
external_link: https://www.nexmo.com/blog/2020/07/20/how-to-receive-an-sms-message-with-asp-net-core-mvc-and-signalr
products:
 - messaging/sms
description: A tutorial to show how your ASP .NET MVC application can use the Nexmo c# library to receive SMS messages from your users and display them in your output window.
languages:
 - dotnet
---
