---
title: How to Send an SMS With ASP.NET Core MVC
external_link: https://www.nexmo.com/blog/2020/07/09/how-to-send-an-sms-with-asp-net-core-mvc
products:
 - messaging/sms
description: Enhance your .NET application by adding the ability to send SMS messages to users. This tutorial walks you through adding a simple form to your web application, and sending an SMS message to the number provided.
languages:
  - dotnet
---
