---
title: "コマンドラインを使用してCSVレポートを作成する"
description: "コマンドラインツールcurlを使用してCSVレポートを作成します。"
products: 
    - "レポート"
introduction: 
    title: "はじめに"
    description: "レポートAPIの使用方法を学びます"
    content: "#はじめに\n\nこのチュートリアルでは、レポートAPIの非同期バージョンを使用してレポートを作成および取得する方法について説明します。\n\nレポートを生成するには、ASYNCエンドポイントにレポート生成リクエストを送信し、それが処理されるのを待ちます。\n\nレポートAPIは、リクエストの形式が正しいかどうかをチェックし、処理キューに配置します。レポートの現在の状態を確認できるリンクを返します。レポートAPIは、レポートが生成されたときにアプリケーションに通知するコールバックを送信することもできます。\n\n>**パフォーマンスに関する注意**：レポートAPIは高速で、膨大な量のデータを処理できますが、リアルタイム分析のためにデータをダウンロードしようとすると処理が遅くなる可能性があります。適切なフィルタを使用すると、処理を大幅に高速化できます。また、データレコードの小さなバッチを頻繁に定期的に取得する場合は、レポートAPIの同期バージョンを使用することを検討してください。\n"
tasks: 
    - "reports/create-report"
    - "reports/check-report-status"
    - "reports/download-report"
    - "reports/reports-whats-next"
