title: Creating a web-based chat app
description: Create a web application that enables users to message each other
products:
  - client-sdk

introduction:
  title: Introduction to this task
  description: This task shows you how to create a web chat application using the JavaScript Client SDK.
  content: |
    # Introduction
    In this task you will learn how to create and configure a Client SDK Application and then code a web app that enables two users to send messages to each other.

    To do this you will create a Conversation and two Users. You will authenticate these Users and then add them to the Conversation as Members.

    Finally, you will implement chat functionality in your application, including the ability to view and send messages and be notified when either party is currently typing.

    The source code is available [on GitHub](https://github.com/nexmo-community/ip-messaging-tutorial).

prerequisites:
  - create-nexmo-account
  - install-nodejs
  - install-nexmo-cli-beta
<<<<<<< HEAD
  - install-node-client-sdk-beta
=======
  - install-node-client-sdk
>>>>>>> 0e55877f0b0d5d5af57dd6bd8bf863313430af35

tasks:
  - client-sdk/create-application
  - client-sdk/create-conversation
  - client-sdk/create-users-ip-messaging
  - client-sdk/add-users-to-conversation-ip-messaging
<<<<<<< HEAD
  - client-sdk/generate-jwts-ip-messaging
=======
  - client-sdk/generate-jwt
>>>>>>> 0e55877f0b0d5d5af57dd6bd8bf863313430af35
  - client-sdk/create-ui-ip-messaging
  - client-sdk/authenticate-users-ip-messaging
  - client-sdk/join-conversation-ip-messaging
  - client-sdk/show-message-history-ip-messaging
  - client-sdk/send-message-ip-messaging
  - client-sdk/typing-indicators-ip-messaging
  - client-sdk/run-application-ip-messaging

conclusion:
  title: What's next?
  description: What else can you do with the Client SDK?
  content: |

    # What's next?
    You can do a lot more with the Client SDK.

    See [Client SDK documentation](/client-sdk/overview).
