title: Handling an inbound PSTN call in your app
description: You make a phone call from a PSTN handset that is received by your web app.
products:
  - client-sdk

introduction: 
  title: Introduction to this task
  description: This task shows you how to handle an inbound call into your web app using the JavaScript Client SDK.
  content: |
    # Introduction
    You learn how to create a Client SDK application and then write the code that allows your web app to handle an inbound PSTN call.

    There are several parts required for this solution. You need to create a webhook server that can process an 
    inbound webhook. You need the web application itself that will notify the service agent of an inbound call and offer 
    the facility to answer it.

    You also need an NCCO that will forward the inbound call from Nexmo to your web application.


prerequisites:
- create-nexmo-account
- install-nodejs
- install-express
- install-nexmo-cli-beta
- install-local-web-server
- install-node-client-sdk-beta
- run-ngrok

tasks:
- client-sdk/create-application
- nexmo-number
- client-sdk/create-user
- client-sdk/generate-jwt
- client-sdk/create-webhook-server-app-to-phone
- client-sdk/phone-to-app-code
- client-sdk/run-phone-to-app

conclusion:
  title: What's next?
  description: What else can you do with the Client SDK?
  content: |

    # What's next?
    You can do a lot more with the Client SDK.

    See [Client SDK documentation](/client-sdk/overview).
