---
# account
"/account/building-blocks": "/account/secret-management/code-snippets/create-a-secret"
"/account/building-blocks/buy-a-number": "/numbers/code-snippets/buy-a-number"
"/account/numbers/building-blocks": "/numbers/code-snippets"
"/account/numbers/building-blocks/buy-a-number": "/numbers/code-snippets/buy-a-number"
"/account/secret-management/building-blocks/revoke-a-secret": "/account/secret-management/code-snippets/revoke-a-secret"
"/account/secret-management/building-blocks/list-all-secrets": "/account/secret-management/code-snippets/list-all-secrets"
"/account/secret-management/building-blocks/fetch-a-secret": "/account/secret-management/code-snippets/fetch-a-secret"

# dispatch
"/dispatch/building-blocks": "/dispatch/code-snippets/before-you-begin"
"/dispatch/building-blocks/install-cli": "/dispatch/code-snippets/install-cli"
"/dispatch/building-blocks/client-library": "/dispatch/code-snippets/client-library"
"/dispatch/building-blocks/create-an-application": "/dispatch/code-snippets/create-an-application"
"/dispatch/building-blocks/send-a-whatsapp-message-with-failover": "/dispatch/code-snippets/send-a-whatsapp-message-with-failover"
"/dispatch/building-blocks/send-a-viber-message-with-failover": "/dispatch/code-snippets/send-a-viber-message-with-failover"
"/dispatch/building-blocks/send-an-mms-with-failover": "/dispatch/code-snippets/send-an-mms-with-failover"
"/dispatch/building-blocks/send-a-facebook-message-with-failover": "/dispatch/code-snippets/send-a-facebook-message-with-failover"

# messaging
"/messaging/sms/building-blocks/before-you-begin": "/messaging/sms/code-snippets/before-you-begin"
"/messaging/sms/building-blocks": "/messaging/sms/code-snippets/send-an-sms"
"/messaging/sms/building-blocks/receive-a-delivery-receipt": "/messaging/sms/guides/delivery-receipts"
"/messaging/sms/building-blocks/send-an-sms": "/messaging/sms/code-snippets/send-an-sms"
"/messaging/sms/building-blocks/send-an-sms-with-unicode": "/messaging/sms/code-snippets/send-an-sms-with-unicode"
"/messaging/sms/building-blocks/receiving-an-sms": "/messaging/sms/code-snippets/receiving-an-sms"
"/messaging/sns/building-blocks/subscribe-a-user": "/messaging/sns/code-snippets/subscribe-a-user"
"/messaging/sns/building-blocks/sending-a-message": "/messaging/sns/code-snippets/sending-a-message"

# messages-and-workflows-apis
"/messages-and-workflows-apis/messages/building-blocks": "/messages/code-snippets/send-an-sms-with-messages-api"
"/messages-and-workflows-apis/workflows/building-blocks": "/dispatch/code-snippets/send-a-message-with-failover"
"/messages-and-workflows-apis/workflows/building-blocks/send-a-message-with-failover": "/dispatch/code-snippets/send-a-facebook-message-with-failover"
"/messages-and-workflows-apis/messages/building-blocks/send-an-sms-with-messages-api": "/messages/code-snippets/send-an-sms-with-messages-api"
"/messages-and-workflows-apis/messages/building-blocks/send-a-viber-service-message": "/messages/code-snippets/send-a-viber-service-message"
"/messages-and-workflows-apis/messages/building-blocks/send-with-facebook-messenger": "/messages/code-snippets/send-with-facebook-messenger"

# messages
"/messages/building-blocks/before-you-begin": "/messages/code-snippets/before-you-begin"
"/messages/building-blocks": "/messages/code-snippets/before-you-begin"
"/messages/building-blocks/send-mms-basic-auth": "/messages/code-snippets/send-mms"
"/messages/building-blocks/install-cli": "/messages/code-snippets/install-cli"
"/messages/building-blocks/create-an-application": "/messages/code-snippets/create-an-application"
"/messages/building-blocks/client-library": "/messages/code-snippets/client-library"
"/messages/building-blocks/configure-webhooks": "/messages/code-snippets/configure-webhooks"
"/messages/building-blocks/inbound-message": "/messages/code-snippets/inbound-message"
"/messages/building-blocks/message-status": "/messages/code-snippets/message-status"
"/messages/building-blocks/send-an-sms-with-messages-api": "/messages/code-snippets/send-an-sms-with-messages-api"
"/messages/building-blocks/send-mms": "/messages/code-snippets/send-mms"
"/messages/building-blocks/send-whatsapp-template": "/messages/code-snippets/send-whatsapp-template"
"/messages/building-blocks/send-a-viber-service-message": "/messages/code-snippets/send-a-viber-service-message"
"/messages/building-blocks/send-with-facebook-messenger": "/messages/code-snippets/send-with-facebook-messenger"
"/messages/code-snippets/send-a-whatsapp-message": "/messages/code-snippets/send-a-whatsapp-message"

# number-insight
"/number-insight/building-blocks": "/number-insight/code-snippets/number-insight-basic"
"/number-insight/building-blocks/before-you-begin": "/number-insight/code-snippets/before-you-begin"
"/numbers/building-blocks": "/numbers/code-snippets/buy-a-number"
"/number-insight/building-blocks/number-insight-basic": "/number-insight/code-snippets/number-insight-basic"
"/number-insight/building-blocks/number-insight-standard": "/number-insight/code-snippets/number-insight-standard"
"/number-insight/building-blocks/number-insight-advanced": "/number-insight/code-snippets/number-insight-advanced"
"/number-insight/building-blocks/number-insight-advanced-async": "/number-insight/code-snippets/number-insight-advanced-async"
"/number-insight/building-blocks/number-insight-advanced-async-callback": "/number-insight/code-snippets/number-insight-advanced-async-callback"

# sms
"/sms/building-blocks": "/messaging/sms/code-snippets/send-an-sms"

# verify
"/verify/building-blocks": "/verify/code-snippets/send-verify-request"
"/verify/building-blocks/before-you-begin": "/verify/code-snippets/before-you-begin"
"/verify/building-blocks/send-verify-request": "/verify/code-snippets/send-verify-request"
"/verify/building-blocks/check-verify-request": "/verify/code-snippets/check-verify-request"
"/verify/building-blocks/cancel-verify-request": "/verify/code-snippets/cancel-verify-request"
"/verify/building-blocks/trigger-next-verification-process": "/verify/code-snippets/trigger-next-verification-process"

# voice
"/voice/building-blocks": "/voice/voice-api/code-snippets/before-you-begin"
"/voice/voice-api/building-blocks": "/voice/voice-api/code-snippets/before-you-begin"
"/voice/building-blocks/connect-a-phone-call": "/voice/voice-api/code-snippets/connect-an-inbound-call"
"/voice/building-blocks/receive-a-phone-call": "/voice/voice-api/code-snippets/receive-an-inbound-call"
"/voice/voice-api/building-blocks/connect-a-phone-call": "/voice/voice-api/code-snippets/connect-an-inbound-call"
"/voice/voice-api/building-blocks/make-a-phone-call": "/voice/voice-api/code-snippets/make-an-outbound-call"
"/voice/voice-api/building-blocks/receive-a-phone-call": "/voice/voice-api/code-snippets/receive-an-inbound-call"
"/voice/voice-api/building-blocks/before-you-begin": "/voice/voice-api/code-snippets/before-you-begin"
"/voice/voice-api/building-blocks/make-an-outbound-call-with-ncco": "/voice/voice-api/code-snippets/make-an-outbound-call-with-ncco"
"/voice/voice-api/building-blocks/connect-an-inbound-call": "/voice/voice-api/code-snippets/connect-an-inbound-call"
"/voice/voice-api/building-blocks/download-a-recording": "/voice/voice-api/code-snippets/download-a-recording"
"/voice/voice-api/building-blocks/earmuff-a-call": "/voice/voice-api/code-snippets/earmuff-a-call"
"/voice/voice-api/building-blocks/handle-user-input-with-dtmf": "/voice/voice-api/code-snippets/handle-user-input-with-dtmf"
"/voice/voice-api/building-blocks/connect-callers-into-a-conference": "/voice/voice-api/code-snippets/connect-callers-into-a-conference"
"/voice/voice-api/building-blocks/make-an-outbound-call": "/voice/voice-api/code-snippets/make-an-outbound-call"
"/voice/voice-api/building-blocks/mute-a-call": "/voice/voice-api/code-snippets/mute-a-call"
"/voice/voice-api/building-blocks/play-an-audio-stream-into-a-call": "/voice/voice-api/code-snippets/play-an-audio-stream-into-a-call"
"/voice/voice-api/building-blocks/play-dtmf-into-a-call": "/voice/voice-api/code-snippets/play-dtmf-into-a-call"
"/voice/voice-api/building-blocks/play-text-to-speech-into-a-call": "/voice/voice-api/code-snippets/play-text-to-speech-into-a-call"
"/voice/voice-api/building-blocks/receive-an-inbound-call": "/voice/voice-api/code-snippets/receive-an-inbound-call"
"/voice/voice-api/building-blocks/record-a-call-with-split-audio": "/voice/voice-api/code-snippets/record-a-call-with-split-audio"
"/voice/voice-api/building-blocks/record-a-call": "/voice/voice-api/code-snippets/record-a-call"
"/voice/voice-api/building-blocks/record-a-conversation": "/voice/voice-api/code-snippets/record-a-conversation"
"/voice/voice-api/building-blocks/record-a-message": "/voice/voice-api/code-snippets/record-a-message"
"/voice/voice-api/building-blocks/retrieve-info-for-a-call": "/voice/voice-api/code-snippets/retrieve-info-for-a-call"
"/voice/voice-api/building-blocks/retrieve-info-for-all-calls": "/voice/voice-api/code-snippets/retrieve-info-for-all-calls"
"/voice/voice-api/building-blocks/transfer-a-call": "/voice/voice-api/code-snippets/transfer-a-call"
"/voice/voice-api/building-blocks/track-ncco-progress": "/voice/voice-api/code-snippets/track-ncco-progress"

# client-sdk
"/client-sdk/in-app-messaging/building-blocks": "/client-sdk/in-app-messaging/overview"
"/client-sdk/in-app-voice/building-blocks/start-call": "/client-sdk/in-app-voice/code-snippets/start-call"
"/client-sdk/in-app-voice/building-blocks/start-server-managed-call": "/client-sdk/in-app-voice/code-snippets/start-server-managed-call"
"/client-sdk/in-app-voice/building-blocks/register-to-incoming-events": "/client-sdk/in-app-voice/code-snippets/register-to-incoming-events"
"/client-sdk/in-app-voice/building-blocks/answer-call": "/client-sdk/in-app-voice/code-snippets/answer-call"
"/client-sdk/in-app-voice/building-blocks/reject-call": "/client-sdk/in-app-voice/code-snippets/reject-call"
"/client-sdk/in-app-voice/building-blocks/hangup-call": "/client-sdk/in-app-voice/code-snippets/hangup-call"
"/client-sdk/in-app-voice/building-blocks/mute-myself": "/client-sdk/in-app-voice/code-snippets/mute-myself"
"/client-sdk/in-app-voice/building-blocks/earmuff-myself": "/client-sdk/in-app-voice/code-snippets/earmuff-myself"
"/client-sdk/in-app-voice/building-blocks/listen-to-call-status": "/client-sdk/in-app-voice/code-snippets/listen-to-call-status"

# audit
"/audit/building-blocks/get-events": "/audit/code-snippets/get-events"
"/audit/building-blocks/get-event": "/audit/code-snippets/get-event"
"/audit/building-blocks/get-events-with-filtering": "/audit/code-snippets/get-events-with-filtering"
"/audit/building-blocks/get-event-types": "/audit/code-snippets/get-event-types"

# redact
"/redact/building-blocks/redact-using-id": "/redact/code-snippets/redact-using-id"

# vbc
"/vonage-business-cloud/number-programmability/building-blocks/vbc-receive-inbound-call": "/vonage-business-cloud/number-programmability/code-snippets/vbc-receive-inbound-call"
"/vonage-business-cloud/number-programmability/building-blocks/vbc-route-to-extension": "/vonage-business-cloud/number-programmability/code-snippets/vbc-route-to-extension"
"/vonage-business-cloud/vbc-apis/extension-api/building-blocks/retrieve-extension": "/vonage-business-cloud/vbc-apis/extension-api/code-snippets/retrieve-extension"
"/vonage-business-cloud/vbc-apis/extension-api/building-blocks/retrieve-extension-list": "/vonage-business-cloud/vbc-apis/extension-api/code-snippets/retrieve-extension-list"
"/vonage-business-cloud/vbc-apis/user-api/building-blocks/retrieve-user": "/vonage-business-cloud/vbc-apis/user-api/code-snippets/retrieve-user"
"/vonage-business-cloud/vbc-apis/user-api/building-blocks/retrieve-user-list": "/vonage-business-cloud/vbc-apis/user-api/code-snippets/retrieve-user-list"

# conversation
"/conversation/building-blocks/conversation/delete-conversation": "/conversation/code-snippets/conversation/delete-conversation"
"/conversation/building-blocks/conversation/list-conversations": "/conversation/code-snippets/conversation/list-conversations"
"/conversation/building-blocks/conversation/create-conversation": "/conversation/code-snippets/conversation/create-conversation"
"/conversation/building-blocks/conversation/update-conversation": "/conversation/code-snippets/conversation/update-conversation"
"/conversation/building-blocks/conversation/get-conversation": "/conversation/code-snippets/conversation/get-conversation"
"/conversation/building-blocks/leg/list-legs": "/conversation/code-snippets/leg/list-legs"
"/conversation/building-blocks/leg/delete-leg": "/conversation/code-snippets/leg/delete-leg"
"/conversation/building-blocks/user/list-users": "/conversation/code-snippets/user/list-users"
"/conversation/building-blocks/user/get-user": "/conversation/code-snippets/user/get-user"
"/conversation/building-blocks/user/list-user-conversations": "/conversation/code-snippets/user/list-user-conversations"
"/conversation/building-blocks/user/update-user": "/conversation/code-snippets/user/update-user"
"/conversation/building-blocks/user/create-user": "/conversation/code-snippets/user/create-user"
"/conversation/building-blocks/user/delete-user": "/conversation/code-snippets/user/delete-user"
"/conversation/building-blocks/event/list-events": "/conversation/code-snippets/event/list-events"
"/conversation/building-blocks/event/get-event": "/conversation/code-snippets/event/get-event"
"/conversation/building-blocks/event/delete-event": "/conversation/code-snippets/event/delete-event"
"/conversation/building-blocks/event/create-event": "/conversation/code-snippets/event/create-event"
"/conversation/building-blocks/member/delete-member": "/conversation/code-snippets/member/delete-member"
"/conversation/building-blocks/member/update-member": "/conversation/code-snippets/member/update-member"
"/conversation/building-blocks/member/get-member": "/conversation/code-snippets/member/get-member"
"/conversation/building-blocks/member/list-members": "/conversation/code-snippets/member/list-members"
"/conversation/building-blocks/member/create-member": "/conversation/code-snippets/member/create-member"