name: Nexmo Developer
subtitle: Nexmo is now Vonage
docs_repo: 'nexmo/nexmo-developer'
oas_repo: 'nexmo/api-specification'
oas_url: https://www.github.com/nexmo/api-specification/blob/master/definitions
