navigation_weight:
  Messaging: 1
  SMS: 1
  Voice: 2
  Verify: 3
  Number Insight: 4
  Messages: 5
  Dispatch: 6
  Numbers: 98
  Account: 99
  Concepts: 0

  Overview: 1
  Developer Preview: 2
  Quickstarts: 3
  Guides: 4
  Building Blocks: 5

  Tutorials: 6
  API Reference: 7
  Conversation: 8

  Voice API: 1
  SIP: 2

  Client SDKs: 30
  NCCO Reference: 40
  SDK Documentation: 40
  API Reference: 50

  Overview: 1
  Concepts: 2
  In-App Messaging: 3
  In-App Voice: 4
  In-App Video: 5

  Messages API: 1
  Dispatch API: 2

  Secret Management: 3

navigation_overrides:
  audit:
    label: 'Beta'
  redact:
    label: 'Developer Preview'
  stitch:
    label: 'Developer Preview'
    sdk-documentation:
      link: false
      prevent_navigation_item_class: true
  voice:
    voice-api:
      guides:
        lex-connector:
          label: 'Developer Preview'
        websockets:
          label: 'Beta'
  messages:
    label: 'Beta'
  dispatch:
    label: 'Beta'
