products:
  - account
  - account/subaccounts
  - application
  - audit
  - client-sdk
  - client-sdk/in-app-voice
  - client-sdk/in-app-video
  - client-sdk/in-app-messaging
  - concepts
  - conversation
  - dispatch
  - messages
<<<<<<< HEAD
=======
  - messaging
>>>>>>> cfba183260cec8e8e824b8325fc77f4412c38d15
  - messaging/sms
  - messaging/conversion-api
  - messaging/us-short-codes
  - number-insight
  - numbers
  - redact
  - reports
  - verify
<<<<<<< HEAD
  - voice/sip
  - voice/voice-api
=======
  - voice
  - voice/sip
  - voice/voice-api
  - vonage-business-cloud
>>>>>>> cfba183260cec8e8e824b8325fc77f4412c38d15
  - vonage-business-cloud/smart-numbers
  - vonage-business-cloud/integration-suite
  - vonage-business-cloud/vbc-apis/account-api
  - vonage-business-cloud/vbc-apis/extension-api
  - vonage-business-cloud/vbc-apis/reports-api
  - vonage-business-cloud/vbc-apis/user-api
