---
# Rename

# Existing
"/stitch": "/stitch/overview"
"/stitch/sdk-documentation/android": "/sdk/stitch/android/"
"/stitch/sdk-documentation/ios": "/sdk/stitch/ios/"
"/stitch/sdk-documentation/javascript": "/sdk/stitch/javascript/"
"/stitch/api-reference": "/api/stitch"
"/stitch/in-app-messaging/guides/1-simple-conversation/javascript": "/stitch/in-app-messaging/guides/simple-conversation/javascript"
"/stitch/in-app-messaging/guides/1-simple-conversation/android": "/stitch/in-app-messaging/guides/simple-conversation/android"
"/stitch/in-app-messaging/guides/1-simple-conversation/ios": "/stitch/in-app-messaging/guides/simple-conversation/ios"
"/stitch/in-app-messaging/guides/1-simple-conversation": "/stitch/in-app-messaging/guides/simple-conversation"
"/stitch/in-app-messaging/guides/2-inviting-members/javascript": "/stitch/in-app-messaging/guides/inviting-members/javascript"
"/stitch/in-app-messaging/guides/2-inviting-members/android": "/stitch/in-app-messaging/guides/inviting-members/android"
"/stitch/in-app-messaging/guides/2-inviting-members/ios": "/stitch/in-app-messaging/guides/inviting-members/ios"
"/stitch/in-app-messaging/guides/2-inviting-members": "/stitch/in-app-messaging/guides/inviting-members"
"/stitch/in-app-messaging/guides/3-utilizing-events/javascript": "/stitch/in-app-messaging/guides/utilizing-events/javascript"
"/stitch/in-app-messaging/guides/3-utilizing-events/android": "/stitch/in-app-messaging/guides/utilizing-events/android"
"/stitch/in-app-messaging/guides/3-utilizing-events/ios": "/stitch/in-app-messaging/guides/utilizing-events/ios"
"/stitch/in-app-messaging/guides/3-utilizing-events": "/stitch/in-app-messaging/guides/utilizing-events"
"/stitch/in-app-voice/guides/1-enable-audio/javascript": "/stitch/in-app-voice/guides/enable-audio/javascript"
"/stitch/in-app-voice/guides/1-enable-audio/android": "/stitch/in-app-voice/guides/enable-audio/android"
"/stitch/in-app-voice/guides/1-enable-audio/ios": "/stitch/in-app-voice/guides/enable-audio/ios"
"/stitch/in-app-voice/guides/1-enable-audio": "/stitch/in-app-voice/guides/enable-audio"
"/stitch/in-app-voice/guides/2-calling-users/javascript": "/stitch/in-app-voice/guides/calling-users/javascript"
"/stitch/in-app-voice/guides/2-calling-users/android": "/stitch/in-app-voice/guides/calling-users/android"
"/stitch/in-app-voice/guides/2-calling-users/ios": "/stitch/in-app-voice/guides/calling-users/ios"
"/stitch/in-app-voice/guides/2-calling-users": "/stitch/in-app-voice/guides/calling-users"
"/stitch/in-app-voice/guides/3-outbound-pstn/javascript": "/stitch/in-app-voice/guides/outbound-pstn/javascript"
"/stitch/in-app-voice/guides/3-outbound-pstn/android": "/stitch/in-app-voice/guides/outbound-pstn/android"
"/stitch/in-app-voice/guides/3-outbound-pstn/ios": "/stitch/in-app-voice/guides/outbound-pstn/ios"
"/stitch/in-app-voice/guides/3-outbound-pstn": "/stitch/in-app-voice/guides/outbound-pstn"
"/stitch/in-app-video/guides/1-enable-video/javascript": "/stitch/in-app-video/guides/enable-video/javascript"
"/stitch/in-app-video/guides/1-enable-video": "/stitch/in-app-video/guides/enable-video"
"/stitch/in-app-video/guides/2-enable-screenshare/javascript": "/stitch/in-app-video/guides/enable-screenshare/javascript"
"/stitch/in-app-video/guides/2-enable-screenshare": "/stitch/in-app-video/guides/enable-screenshare"
"/sdk/stitch/ios": "/sdk/stitch/ios/"
"/stitch/in-app-voice/ncco-guide": "/stitch/in-app-voice/guides/ncco-guide"
"/stitch/in-app-voice/inbound-pstn": "/stitch/in-app-voice/guides/inbound-pstn"
