current:
  - name: 'Kelly Andrews'
    email: 'kelly.andrews@vonage.com'
    twitter: 'kellyjandrews'
  - name: 'Myrsini Koukiasa'
    email: 'myrsini.koukiasa@vonage.com'
    twitter: 'myrsiningos'
    role: 'Senior Community Manager'
  - name: 'Garann Means'
    email: 'garann.means@vonage.com'
  - name: 'Paul Ardeleanu'
    email: 'paul.ardeleanu@vonage.com'
    twitter: 'pardel'
  - name: 'Fabian Rodriguez'
    email: 'fabian.rodriguez@vonage.com'
    twitter: 'fabianrbz'
    role: 'Vonage API Developer Tech Lead'
  - name: 'Laura Czajkowski'
    email: 'laura.czajkowski@vonage.com'
    twitter: 'Czajkowski'
    role: 'Developer Relations Manager'
  - name: 'Bethany Loft'
    email: 'bethany.loft@vonage.com'
    twitter: 'bb_loft'
    role: 'Community Manager'
  - name: 'Dwane Hemmings'
    email: 'dwane.hemmings@vonage.com'
    twitter: 'dwaneio'
    twitter: 'michaeljolley'
  - name: 'Nick Iati'
    email: 'nick.iati@vonage.com'
    role: 'Technical Writer'
  - name: 'Benjamin Aronov'
    email: 'benjamin.aronov@vonage.com'
    role: 'Online Community Manager'
  - name: "Igor Wojda"
    email: "igor.wojda@vonage.com"
    twitter: "igorwojda"
  - name: "Abdul Ajetunmobi"
    email: "abdul.ajetunmobi@vonage.com"
    twitter: "abdulajet"
  - name: "Clarisse Ng"
    email: "clarisse.ng@vonage.com"
    role: "Community Manager, APAC"
  - name: "Avital Tzubeli"
    email: "avital.tzubeli@vonage.com"
    role: "Regional Developer Advocate"
  - name: "Filippos Kyprianou"
    email: "filippos.kyprianou@vonage.com"
    role: "Startup Community Manager"
  - name: "Cory Althoff"
    email: "cory.althoff@vonage.com"
    role: "Developer Advocate"
    twitter: "coryalthoff"  
