
title: "Welcome to the Nexmo Client SDK"
meta_title: "This is the Nexmo Client SDK for JavaScript, Android, and iOS, for voice and messaging applications."

page:
  - row:
    - column: 
      - type: header
        header:
          title: 
            text: "Welcome to the Nexmo Client SDK"
            align: center
          subtitle:
            text: "This is the Nexmo Client SDK for JavaScript, Android, and iOS, for voice and messaging applications."
            align: center
            type: large
          icon: 
            name: "icon-star"
            color: "yellow"
  - row:
    - column:
      - type: call_to_action
        call_to_action:
          title: Getting Started Guide
          subtitle: Shows you how to get started with the Nexmo Client SDK.
          icon: 
            name: "icon-design-tools"
            color: "blue-dark"
          url: /task/client-sdk-getting-started/introduction
