# Default landing config page

# Column Types: header, building_block, call_to_action, developer_resources, text, html

# building_block: name (i.e. messaging/sms), language (i.e. ruby), pretext, posttext
# call_to_action: header, icon, subheader
# developer_resources: type (i.e. tutorial, sdk), name
# text: text
# html: html

# columns width: if "width" is not provided then default to 100%

title: "Welcome to Nexmo, Residents of Jupiter"
meta_title: "A longer title goes here."

rows:
  - columns:
    - entries: 
      - type: header
        header:
          title: "Thanks for joining us!"
          subtitle: "So glad you made it to OneHack Jupiter!"
          icon: "onehack-icon"
  - columns:
    - width: 2
      entries:
      - type: building_block
        building_block:
          name: messaging/sms
          language: ruby
          pre_text:
          post_text:
    - width: 2
      entries:
      - type: building_block
        building_block:
          name: messaging/send-an-sms
          language: python
          pre_text:
          post_text:
  - columns:
    - width: 1 
      entries:
      - type: call_to_action
        call_to_action:
          header: "Sign Up"
          icon: "sign-up"
          subheader: "Try it for free"
    - width: 1
      entries: 
      - type: join_slack
    - width: 1
      entries: 
      - type: github_org
        github_org:
          name: nexmo
    - width: 1
      entries:
      - type: github_repo
        github_repo:
          org: nexmo
          name: nexmo-php
  - columns: 
    - width: 1
      entries:
      - type: developer_resources
        developer_resources:
          type: tutorial
          name: call-tracking
    - width: 1
      entries:
      - type: developer_resources
        developer_resources:
          type: tutorial
          name: receive-sms-with-ruby
    - width: 2 
      entries:
      - type: developer_resources
        developer_resources:
          type: sdk
          name: ruby
  - columns: 
    - width: 1
      entries: 
      - type: text
        text:
          content: Your awesome content
    - width: 1
      entries:
      - type: text
        text:
          content: More awesome content
    - width: 1
      entries:
      - type: html
        html:
          content: <a href="/find/me/here">Amazing things</a>
    - width: 1
      entries:
      - type: structured_text
        structured_text:
          header: "This is the header text"
          icon: "icon-lightbulb"
          text:
            - main_text: "This is bigger text."
            - small_text: "This is small text block."
            - small_text: "This is another small text block underneath it."