name: Smartling Uploader for Files Changed within 5 Days
on:
  schedule:
    - cron: "0 0 */5 * *"
  workflow_dispatch:
    branches:
      - main
jobs:
  check-changes:
    runs-on: ubuntu-latest
    services:
      db:
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: nexmo_developer_test
          POSTGRES_HOST_AUTH_METHOD: trust
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Find yarn cache location
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: JS package cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install packages
      run: |
        yarn install --pure-lockfile
    - name: Set up Ruby 2.7.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: Ruby gem cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install postgres headers
      run: sudo apt-get -yqq install libpq-dev
    - name: Bundle Install
      env:
        POSTGRES_USERNAME: postgres
        BUNDLE_RUBYGEMS__PKG__GITHUB__COM: "NexmoDev:${{ secrets.GH_ADMIN_TOKEN }}"
      run: |
        gem update --system 3.1.4 -N
        gem install --no-document bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - id: step1
      name: Check for File Changes
      run: |
        arr=$(RAILS_LOG_TO_STDOUT=1 RAILS_ENV=test bundle exec nexmo-developer --docs=. --rake-check-docs-changes 5)
        arr=${arr#*successfully.}
        echo ::set-output name=file_changes::"$(echo $(sed 's/\n/ /g' <<< $arr))"
      env:
        POSTGRES_USERNAME: postgres
        DOCS_BASE_PATH: "."
        OAS_PATH: "_open_api/api_specs/definitions"
        FORCE_COLOR: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run rake task
      if: steps.step1.outputs.file_changes != ''
      env:
        SMARTLING_USER_ID: ${{ secrets.SMARTLING_USER_ID }}
        SMARTLING_USER_SECRET: ${{ secrets.SMARTLING_USER_SECRET }}
        SMARTLING_PROJECT_ID: ${{ secrets.SMARTLING_PROJECT_ID }}
        POSTGRES_USERNAME: postgres
        OAS_PATH: "_open_api/api_specs/definitions"
        FORCE_COLOR: true
      run: |
        echo "FILE CHANGES:"
        echo ${{steps.step1.outputs.file_changes}}
        RAILS_LOG_TO_STDOUT=1 RAILS_ENV=test bundle exec nexmo-developer --docs=. --rake-smartling-upload 5 ${{steps.step1.outputs.file_changes}}
